x-java-entrypoint: &java_entrypoint
  - "java"
  - "-javaagent:/agent/inspectit-gepard-agent.jar"
  - "-Dinspectit.config.http.url=${INSPECTIT_GEPARD_CONFIGSERVER_ADDRESS}"
  - "-Dlogging.level.root=${INSPECTIT_GEPARD_LOGLEVEL}"
  - "org.springframework.boot.loader.launch.JarLauncher"

services:
  # PetClinic
  config-server:
    image: ${PETCLINIC_IMAGE}-config-server:${PETCLINIC_VERSION}
    container_name: config-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      agent:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-I", "http://config-server:8888"]
      interval: 20s
      timeout: 5s
      retries: 10
    volumes:
      - agent-vol:/agent
    entrypoint: *java_entrypoint
    ports:
      - 8888:8888
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://${OTEL_COLLECTOR_HOST}:${OTEL_COLLECTOR_PORT_HTTP}
      - OTEL_SERVICE_NAME=config-server
      - INSPECTIT_CONFIG_HTTP_ATTRIBUTES_APPLICATION=petclinic
      - INSPECTIT_CONFIG_HTTP_ATTRIBUTES_ROLE=operation

  discovery-server:
    image: ${PETCLINIC_IMAGE}-discovery-server:${PETCLINIC_VERSION}
    container_name: discovery-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://discovery-server:8761"]
      interval: 20s
      timeout: 3s
      retries: 10
    depends_on:
      config-server:
        condition: service_healthy
    volumes:
      - agent-vol:/agent
    entrypoint: *java_entrypoint
    ports:
      - 8761:8761
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://${OTEL_COLLECTOR_HOST}:${OTEL_COLLECTOR_PORT_HTTP}
      - OTEL_SERVICE_NAME=discovery-service
      - INSPECTIT_CONFIG_HTTP_ATTRIBUTES_APPLICATION=petclinic
      - INSPECTIT_CONFIG_HTTP_ATTRIBUTES_ROLE=operation

  customers-service:
    image: ${PETCLINIC_IMAGE}-customers-service:${PETCLINIC_VERSION}
    container_name: customers-service
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://customers-service:8081/actuator/health"]
      interval: 20s
      timeout: 3s
      retries: 20
    volumes:
      - agent-vol:/agent
    entrypoint: *java_entrypoint
    ports:
      - 8081:8081
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://${OTEL_COLLECTOR_HOST}:${OTEL_COLLECTOR_PORT_HTTP}
      - OTEL_SERVICE_NAME=customers-service
      - INSPECTIT_CONFIG_HTTP_ATTRIBUTES_APPLICATION=petclinic
      - INSPECTIT_CONFIG_HTTP_ATTRIBUTES_ROLE=business

  visits-service:
    image: inspectit/spring-petclinic-visits-service:${PETCLINIC_VERSION}
    container_name: visits-service
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://visits-service:8082/actuator/health"]
      interval: 20s
      timeout: 3s
      retries: 20
    volumes:
      - agent-vol:/agent
    entrypoint: *java_entrypoint
    ports:
      - 8082:8082
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://${OTEL_COLLECTOR_HOST}:${OTEL_COLLECTOR_PORT_HTTP}
      - OTEL_SERVICE_NAME=visits-service
      - INSPECTIT_CONFIG_HTTP_ATTRIBUTES_APPLICATION=petclinic
      - INSPECTIT_CONFIG_HTTP_ATTRIBUTES_ROLE=business

  vets-service:
    image: ${PETCLINIC_IMAGE}-vets-service:${PETCLINIC_VERSION}
    container_name: vets-service
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://vets-service:8083/actuator/health"]
      interval: 20s
      timeout: 3s
      retries: 20
    volumes:
      - agent-vol:/agent
    entrypoint: *java_entrypoint
    ports:
      - 8083:8083
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://${OTEL_COLLECTOR_HOST}:${OTEL_COLLECTOR_PORT_HTTP}
      - OTEL_SERVICE_NAME=vets-service
      - INSPECTIT_CONFIG_HTTP_ATTRIBUTES_APPLICATION=petclinic
      - INSPECTIT_CONFIG_HTTP_ATTRIBUTES_ROLE=business

  api-gateway:
    image: ${PETCLINIC_IMAGE}-api-gateway:${PETCLINIC_VERSION}
    container_name: api-gateway
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    ports:
      - 8099:8080
    volumes:
      - agent-vol:/agent
    entrypoint: *java_entrypoint
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://${OTEL_COLLECTOR_HOST}:${OTEL_COLLECTOR_PORT_HTTP}
      - OTEL_SERVICE_NAME=api-gateway
      - INSPECTIT_CONFIG_HTTP_ATTRIBUTES_APPLICATION=petclinic
      - INSPECTIT_CONFIG_HTTP_ATTRIBUTES_ROLE=business
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api-gateway:8080/actuator/health"]
      interval: 20s
      timeout: 5s
      retries: 10

  admin-server:
    image: ${PETCLINIC_IMAGE}-admin-server:${PETCLINIC_VERSION}
    container_name: admin-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    ports:
      - 9000:9090

  # InspectIT
  agent:
    image: ${INSPECTIT_GEPARD_AGENT_IMAGE}:${INSPECTIT_GEPARD_AGENT_VERSION}
    container_name: agent
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    depends_on:
      inspectit-configserver:
        condition: service_healthy
    volumes:
      - agent-vol:/agent

  inspectit-configserver:
    image: ${INSPECTIT_GEPARD_CONFIGSERVER_IMAGE}:${INSPECTIT_GEPARD_CONFIGSERVER_VERSION}
    container_name: ${INSPECTIT_GEPARD_CONFIGSERVER_HOST}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
      - 8080:8080
      - 8091:9090
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "--Insecure",
          "http://inspectit-configserver:9090/actuator/swagger-ui",
        ]
      interval: 5s
      timeout: 3s
      retries: 10

  # Collector
  otelcol:
    image: ${COLLECTOR_CONTRIB_IMAGE}
    container_name: otelcol
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 200M
    command:
      [
        "--config=/etc/otelcol-config.yml",
        "--config=/etc/otelcol-config-extras.yml",
      ]
    user: 0:0
    volumes:
      - ${HOST_FILESYSTEM}:/hostfs:ro
      - ${DOCKER_SOCK}:/var/run/docker.sock:ro
      - ${OTEL_COLLECTOR_CONFIG}:/etc/otelcol-config.yml
      - ${OTEL_COLLECTOR_CONFIG_EXTRAS}:/etc/otelcol-config-extras.yml
    ports:
      - "${OTEL_COLLECTOR_PORT_GRPC}"
      - "${OTEL_COLLECTOR_PORT_HTTP}"
    depends_on:
      - jaeger
    environment:
      - ENVOY_PORT
      - HOST_FILESYSTEM
      - OTEL_COLLECTOR_HOST
      - OTEL_COLLECTOR_PORT_GRPC
      - OTEL_COLLECTOR_PORT_HTTP
      - INFLUXDB_TOKEN
      - INFLUXDB_ORG
      - INFLUXDB_BUCKET
      - INFLUXDB_ADDRESS

  #  logging: *logging

  jaeger:
    image: ${JAEGERTRACING_IMAGE}
    container_name: jaeger
    restart: unless-stopped
    command:
      - "--memory.max-traces=5000"
      - "--query.base-path=/jaeger/ui"
    deploy:
      resources:
        limits:
          memory: 400M
    ports:
      - "${JAEGER_SERVICE_PORT}:${JAEGER_SERVICE_PORT}" # Jaeger UI
      - "${OTEL_COLLECTOR_PORT_GRPC}"

  influxdb:
    image: ${INFLUXDB_IMAGE}
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}

  prometheus:
    image: ${PROMETHEUS_IMAGE}
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./src/prometheus:/etc/prometheus

  timescaledb:
    image: ${TIMESCALEDB_IMAGE}
    container_name: timescaledb
    restart: unless-stopped
    environment:
      POSTGRES_USER: inspectit
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inspectit
    ports:
      - "5432:5432"

  grafana:
    image: ${GRAFANA_IMAGE}
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./src/grafana/provisioning:/usr/share/grafana/custom/
      - ./src/grafana/dashboards:/usr/share/grafana/public/dashboards
    environment:
      - GF_PATHS_PROVISIONING=/usr/share/grafana/custom/
      - INFLUXDB_TOKEN
      - INFLUXDB_ORG
      - INFLUXDB_BUCKET
      - INFLUXDB_ADDRESS

  grafana-tempo:
    image: ${GRAFANA_TEMPO_IMAGE}
    container_name: grafana-tempo
    restart: unless-stopped
    command: [ "-config.file=/etc/tempo.yml" ]
    ports:
      - "3200:3200"
    volumes:
      - ./src/grafana/tempo/tempo.yml:/etc/tempo.yml
      - tempo-storage:/var/tempo
    depends_on:
      memcached:
        condition: service_started

  memcached:
    image: memcached:1.6.29
    container_name: memcached
    restart: unless-stopped
    ports:
      - "11211:11211"
    environment:
      - MEMCACHED_MAX_MEMORY=64m
      - MEMCACHED_THREADS=4

  # Load Generator
  loadgenerator:
    image: ${LOAD_GENERATOR_IMAGE_NAME}:${LOAD_GENERATOR_IMAGE_VERSION}
    container_name: loadgenerator
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ${LOAD_GENERATOR_DOCKERFILE}
      cache_from:
        - ${LOAD_GENERATOR_IMAGE_NAME}:${LOAD_GENERATOR_IMAGE_VERSION}
    deploy:
      resources:
        limits:
          memory: 1G
    ports:
      - ${LOCUST_WEB_PORT}:${LOCUST_WEB_PORT}
    environment:
      - LOCUST_WEB_PORT
      - LOCUST_USERS
      - LOCUST_HOST=${PETCLINIC_GATEWAY}
      - LOCUST_HEADLESS
      - LOCUST_AUTOSTART
      - LOCUST_BROWSER_TRAFFIC_ENABLED=true
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
      - OTEL_RESOURCE_ATTRIBUTES
      - OTEL_SERVICE_NAME=loadgenerator
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
      - LOCUST_WEB_HOST=0.0.0.0
    depends_on:
      api-gateway:
        condition: service_healthy
      customers-service:
        condition: service_healthy
      visits-service:
        condition: service_healthy
      vets-service:
        condition: service_healthy

volumes:
  agent-vol:
  influxdb:
  grafana-storage:
  tempo-storage:
