{
 "title": "Infrastructure Monitoring",
 "tags": [
  "open-telemetry",
  "cpu",
  "memory"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "service_name", "label": "Service", "query": { "query": "label_values(exported_job)" } }
  ]
 },
 "panels": [
  { "title": "$service_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "service_name" },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(jvm_cpu_recent_utilization_ratio{exported_job=\"$service_name\"}[$__interval])",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(jvm_memory_used_bytes{exported_job=\"$service_name\",jvm_memory_type=\"heap\"}[$__interval]))",
     "legendFormat": "used"
    },
    {
     "expr": "sum(avg_over_time(jvm_memory_limit_bytes{exported_job=\"$service_name\", jvm_memory_type=\"heap\"}[$__interval]))",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(avg_over_time(jvm_memory_committed_bytes{exported_job=\"$service_name\", jvm_memory_type=\"heap\"}[$__interval]))",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "Non-Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(jvm_memory_used_bytes{exported_job=\"$service_name\",jvm_memory_type=\"non_heap\"}[$__interval]))",
     "legendFormat": "used"
    },
    {
     "expr": "sum(avg_over_time(jvm_memory_limit_bytes{exported_job=\"$service_name\", jvm_memory_type=\"non_heap\"}[$__interval]))",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(avg_over_time(jvm_memory_committed_bytes{exported_job=\"$service_name\", jvm_memory_type=\"non_heap\"}[$__interval]))",
     "legendFormat": "committed"
    }
   ]
  }
 ]
}