{
 "title": "JVM Monitoring",
 "tags": [
  "JVM",
  "open-telemetry",
  "Java"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "service_name", "label": "Service", "query": { "query": "label_values(exported_job)" } }
  ]
 },
 "panels": [
  { "title": "$service_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "service_name" },
  {
   "title": "Total Java Classes",
   "type": "stat",
   "gridPos": { "h": 16, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_class_count{exported_job=\"$service_name\"}",
     "legendFormat": "current classes of {{exported_job}}"
    },
    {
     "expr": "jvm_class_loaded_total{exported_job=\"$service_name\"}",
     "legendFormat": "loaded classes of {{exported_job}}"
    },
    {
     "expr": "jvm_class_unloaded_total{exported_job=\"$service_name\"}",
     "legendFormat": "unloaded classes of {{exported_job}}"
    }
   ]
  },
  {
   "title": "Thread states",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "avg_over_time(jvm_thread_count{exported_job=\"$service_name\"}[$__interval])",
     "legendFormat": "{{jvm_thread_state}} (deamon: {{jvm_thread_daemon}})"
    }
   ]
  },
  {
   "title": "Minor Garbage Collection Avg Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_duration_seconds_sum{exported_job=\"$service_name\"}[$__rate_interval]) / rate(jvm_gc_duration_seconds_count{exported_job=\"$service_name\"}[$__rate_interval])",
     "legendFormat": "{{jvm_gc_action}}"
    }
   ]
  }
 ]
}