apiVersion: 1
datasources:
  - orgId: 1
    name: InfluxDB
    type: influxdb
    access: proxy
    url: $INFLUXDB_ADDRESS
    jsonData:
      version: Flux
      organization: $INFLUXDB_ORG
      defaultBucket: $INFLUXDB_BUCKET
      tlsSkipVerify: true
    secureJsonData:
      token: $INFLUXDB_TOKEN